[package]
name = "gtk-sys"
version = "0.1.0"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "gtk"

description = "FFI bindings to GTK+ 3"
repository = "https://github.com/rust-gnome/gtk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gtk"
documentation = "https://github.com/rust-gnome/gtk"

[lib]
name = "gtk_sys"

[features]
gtk_3_4 = []
gtk_3_6 = []
gtk_3_8 = []
gtk_3_10 = []
gtk_3_12 = []
gtk_3_14 = []

[dependencies]
libc = "0.1"
glib-sys = "^0"
gdk-sys = "^0"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"
