language: rust
sudo: true
env:
  global:
    - secure: cRbvQ7JYJzUdxjf1XJIQuCIwrvZbLxNUYkSfKfnRrqnbFKXNWW8cKBFaVQWPwmDrocGBwZVEsYPxra88dZtro0NIRmRuZzZ2jZfbCeatGPveQGGxsst9a5UXX8LYnk7w3M4aOLtIgjG90vD+FgyouhZdPZwCGEodtGYieeLnwrM=
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - sudo apt-get install libgtk-3-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone --depth 1 https://github.com/rust-gnome/examples _test
  - cd _test
  - cargo build
  - cd ..
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
