language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=latest
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - ./check_init_asserts
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/rust-gnome/examples _examples
  - cd _examples
  - ./build.sh
