language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - ./check_init_asserts
  - cargo install clippy || touch clippy_failed
  - if [ ! -f clippy_failed ]; then cargo clippy; fi
  - cargo test --features embed-lgpl-docs --jobs 1
  # catch any sneaked in lgpl docs
  - cargo build --features purge-lgpl-docs --jobs 1
  - git diff -R --exit-code
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build.sh
