language: rust
rust:
- nightly
- stable
sudo: true
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - sudo apt-get install libgtk-3-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 1 https://github.com/rust-gnome/examples _examples
  - cd _examples
  - ./git_deps.sh cairo glib gdk pango
  - cargo build
  - cd ..
  - cargo doc
