env:
  global:
    - secure: cRbvQ7JYJzUdxjf1XJIQuCIwrvZbLxNUYkSfKfnRrqnbFKXNWW8cKBFaVQWPwmDrocGBwZVEsYPxra88dZtro0NIRmRuZzZ2jZfbCeatGPveQGGxsst9a5UXX8LYnk7w3M4aOLtIgjG90vD+FgyouhZdPZwCGEodtGYieeLnwrM=
    - LD_LIBRARY_PATH=/usr/local/lib
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - GTK_VERSION=GTK_3_6; export GTK_VERSION
  - cargo build --features GTK_3_6
  - cd examples
  - cd basic && cargo build
  - cd ../cairotest && cargo build
  - cd ../sync_widgets && cargo build
  - cd ../text_viewer && cargo build
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh