environment:
  matrix:
    - RUST: 1.8.0
      BITS: 32
    - RUST: 1.8.0
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST%-%ARCH%-pc-windows-gnu.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V
  - pacman --noconfirm -S mingw-w64-%ARCH%-gtk3

build_script:
  - mkdir .cargo
  - echo paths = ["."] > .cargo\config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - cargo build
  - cargo build --features gtk_3_18

test: false
