[package]
documentation = "http://gtk-rs.org/docs/gtk/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK+ 3 library"
name = "gtk"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
readme = "README.md"
version = "0.4.0"
keywords = ["gtk", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/gtk", service = "github" }
travis-ci = { repository = "gtk-rs/gtk" }

[lib]
name = "gtk"

[features]
v3_6 = ["gtk-sys/v3_6", "gdk/v3_6"]
v3_20 = ["v3_18", "gtk-sys/v3_20", "gdk/v3_20"]
v3_18 = ["v3_16", "gtk-sys/v3_18", "gdk/v3_18"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
v3_22 = ["v3_20", "gtk-sys/v3_22", "gdk/v3_22"]
v3_22_20 = ["v3_22", "gtk-sys/v3_22_26", "gdk/v3_22"]
v3_22_26 = ["v3_22_20", "gtk-sys/v3_22_26", "gdk/v3_22"]
v3_12 = ["v3_10", "gtk-sys/v3_12", "gdk/v3_12"]
v3_8 = ["v3_6", "gtk-sys/v3_8", "gdk/v3_8"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
v3_16 = ["v3_14", "gtk-sys/v3_16", "gdk/v3_16"]
v3_10 = ["v3_8", "gtk-sys/v3_10", "gdk/v3_10"]
v3_14 = ["v3_12", "gtk-sys/v3_14", "gdk/v3_14"]
dox = ["gdk/dox", "gtk-sys/dox"]
futures = ["futures-core", "send-cell", "gio/futures"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"
send-cell = { version = "0.1", optional = true }
futures-core = { version = "0.2", optional = true }

[dependencies.cairo-sys-rs]
version = "0.6.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.gdk-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gdk-pixbuf-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gtk-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.cairo-rs]
version = "0.4.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.gio]
version = "0.4.0"
git = "https://github.com/gtk-rs/gio"

[dependencies.glib]
version = "0.5.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.gdk]
version = "0.8.0"
git = "https://github.com/gtk-rs/gdk"

[dependencies.gdk-pixbuf]
version = "0.4.0"
git = "https://github.com/gtk-rs/gdk-pixbuf"

[dependencies.pango]
version = "0.4.0"
git = "https://github.com/gtk-rs/pango"
