[package]
documentation = "http://gtk-rs.org/docs/gtk/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK+ 3 library"
name = "gtk"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
readme = "README.md"
version = "0.4.0"
keywords = ["gtk", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/gtk", service = "github" }
travis-ci = { repository = "gtk-rs/gtk" }

[lib]
name = "gtk"

[features]
v3_6 = ["gtk-sys/v3_6", "gdk/v3_6"]
v3_20 = ["v3_18", "gtk-sys/v3_20", "gdk/v3_20"]
v3_18 = ["v3_16", "gtk-sys/v3_18", "gdk/v3_18"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
v3_22 = ["v3_20", "gtk-sys/v3_22", "gdk/v3_22"]
v3_22_20 = ["v3_22", "gtk-sys/v3_22_26", "gdk/v3_22"]
v3_22_26 = ["v3_22_20", "gtk-sys/v3_22_26", "gdk/v3_22"]
v3_12 = ["v3_10", "gtk-sys/v3_12", "gdk/v3_12"]
v3_8 = ["v3_6", "gtk-sys/v3_8", "gdk/v3_8"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
v3_16 = ["v3_14", "gtk-sys/v3_16", "gdk/v3_16"]
v3_10 = ["v3_8", "gtk-sys/v3_10", "gdk/v3_10"]
v3_14 = ["v3_12", "gtk-sys/v3_14", "gdk/v3_14"]
dox = ["gdk/dox", "gtk-sys/dox"]

[target.'cfg(target_os = "macos")'.build-dependencies]
cc = "^1.0"

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true

[dependencies]
cairo-rs = "0.4.0"
cairo-sys-rs = "0.6.0"
gobject-sys = "0.6.0"
glib-sys = "0.6.0"
glib = "0.5.0"
gio-sys = "0.6.0"
gio = "0.4.0"
gdk-sys = "0.6.0"
gdk = "0.8.0"
gdk-pixbuf-sys = "0.6.0"
gdk-pixbuf = "0.4.0"
pango = "0.4.0"
gtk-sys = "0.6.0"
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"
