[package]
name = "rgtk"
version = "0.0.1"
authors = ["letang.jeremy@gmail.com", "guillaume1.gomez@gmail.com", "mathijs.henquet@gmail.com", "bpgarman@fastmail.fm", "me@bstr.eu", "zsoakes@gmail.com"]
build = "build.rs"

[features]
GTK_3_14 = []
GTK_3_12 = []
GTK_3_10 = []
GTK_3_8 = []
GTK_3_6 = []

[lib]
name = "rgtk"
crate_type = ["rlib"]
path = "src/rgtk.rs"
