[package]
name = "gtk"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

categories = ["api-bindings", "gui"]
description = "Rust bindings for the GTK+ 3 library"
repository = "https://github.com/gtk-rs/gtk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gtk/"

keywords = ["gtk", "gtk-rs", "gnome", "GUI"]

[badges]
appveyor = { repository = "GuillaumeGomez/gtk", service = "github" }
travis-ci = { repository = "gtk-rs/gtk" }

[lib]
name = "gtk"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
v3_6 = ["gtk-sys/v3_6", "gdk/v3_6"]
v3_8 = ["v3_6", "gtk-sys/v3_8", "gdk/v3_8"]
v3_10 = ["v3_8", "gtk-sys/v3_10", "gdk/v3_10"]
v3_12 = ["v3_10", "gtk-sys/v3_12", "gdk/v3_12"]
v3_14 = ["v3_12", "gtk-sys/v3_14", "gdk/v3_14"]
v3_16 = ["v3_14", "gtk-sys/v3_16", "gdk/v3_16"]
v3_18 = ["v3_16", "gtk-sys/v3_18", "gdk/v3_18"]
v3_20 = ["v3_18", "gtk-sys/v3_20", "gdk/v3_20"]
v3_22 = ["v3_20", "gtk-sys/v3_22", "gdk/v3_22"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "^0.1.1"
optional = true

[dependencies]
libc = "0.2"
bitflags = "0.5"
cairo-sys-rs = "^0.3.3"
gdk-sys = "^0.3.3"
gdk-pixbuf-sys = "^0.3.3"
gio-sys = "^0.3.3"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk-sys = "^0.3.3"
cairo-rs = "^0.1.2"
gio = "^0.1.2"
glib = "^0.1.2"
gdk = "^0.5.2"
gdk-pixbuf = "^0.1.2"
pango = "^0.1.2"
