[package]
name = "rgtk"
version = "0.0.1"
authors = ["letang.jeremy@gmail.com", "guillaume1.gomez@gmail.com", "mathijs.henquet@gmail.com", "bpgarman@fastmail.fm", "me@bstr.eu", "zsoakes@gmail.com"]
build = "build.rs"

description = "A rust binding for the GTK+ library"
repository = "https://github.com/jeremyletang/rgtk"
license = "LGPL-3.0+"

[dependencies]
c_vec = "^1.0.0"

[features]
GTK_3_14 = []
GTK_3_12 = []
GTK_3_10 = []
GTK_3_8 = []
GTK_3_6 = []

[lib]
name = "rgtk"
crate_type = ["rlib"]
path = "src/rgtk.rs"

[build-dependencies.pkg-config]
pkg-config = "^0.0.0"

[build-dependencies.gcc]
gcc = "^0.0.0"
