[package]
name = "gtk"
version = "0.0.8"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GTK+ 3 library"
repository = "https://github.com/gtk-rs/gtk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gtk/"

keywords = ["gtk", "gtk-rs", "gnome", "GUI"]

[lib]
name = "gtk"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
v3_6 = ["gtk-sys/v3_6", "gdk/v3_6"]
v3_8 = ["v3_6", "gtk-sys/v3_8", "gdk/v3_8"]
v3_10 = ["v3_8", "gtk-sys/v3_10", "gdk/v3_10"]
v3_12 = ["v3_10", "gtk-sys/v3_12", "gdk/v3_12"]
v3_14 = ["v3_12", "gtk-sys/v3_14", "gdk/v3_14"]
v3_16 = ["v3_14", "gtk-sys/v3_16", "gdk/v3_16"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.1.0"
optional = true

[dependencies]
libc = "0.2"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.3.0"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.0.9"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.9"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
version = "0.4.0"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"
version = "0.0.2"

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"
version = "0.0.8"
