[package]
name = "rgtk-examples"
version = "0.0.1"
authors = []

[dependencies.rgtk]
path = "../"

[[bin]]
name = "gtktest"

[[bin]]
name = "cairotest"

[[bin]]
name = "basic"

[[bin]]
name = "sync_widgets"

[[bin]]
name = "text_viewer"

[[bin]]
name = "treeview"
